### ISSUE TITLE
Not rendering when only one optgroup with one option is present

### ISSUE THREAD

**Issue by lopezcjf** [xavierfaucon/bootstrap-selectsplitter#1]
Hi,
We found a situation in which bootstrap-selectsplitter is not rendering both lists well if we have the following scenario:
- the select input has only one optgroup with only one option

You can easily reproduce this using your online demo here: http://jsfiddle.net/ae7fxdyy/
Just remove Category 2 and 3 groups and leave Category 1 with only "choice 1"

... or just check in this edited jsfiddle: http://jsfiddle.net/lopezcjf/nff30xtv/

Instead of the normal behavior, both are shown as dropdown lists and the right one has no selectable option

Regards
Javier

**Comment by X13454** [comment]
Hi, I'll look into that tomorrow.

**Comment by X13454** [comment]
Hello,

The problem looks resolved with size attribute set to 2 minimum for both select tags.

http://jsfiddle.net/nff30xtv/4/

If it's ok on your side, I'll close this issue.

**Comment by lopezcjf** [comment]
Seems to work fine now. thanks!
