### ISSUE TITLE
Wrong parent selection

### ISSUE THREAD

**Issue by fgiorgio** [xavierfaucon/bootstrap-selectsplitter#11]
Wrong parent is selected on load if the `optgroup` `label` of the selected element is contained in the `label` of another `optgroup`.

For example: "Category" and "Category 3"

Link to reproduce the bug: https://jsfiddle.net/waybn4zp/

**Comment by X13454** [comment]
Hello,

Thanks for your feedback and your commit.

Cheers,

Xavier
