### ISSUE TITLE
How can I open third selector

### ISSUE THREAD

**Issue by hubeyb** [xavierfaucon/bootstrap-selectsplitter#4]
How can I open third selector?

**Comment by X13454** [comment]
Hello,

Could you please give me a little more expanation? By third selector you mean three chained select?
Otherwise please link me a fiddle to show me the problem.

**Comment by hubeyb** [comment]
yes, now only can put 2 selectbox, but I want to add three chained select.

**Comment by X13454** [comment]
Unfortunately it won't be possible with bootstrap-selectsplitter as there are only 2 possible levels for the select on which is applied this plugin (optgroup is first level and its child elements are the second level). 

Maybe this plugin could answer your need: http://www.appelsiini.net/projects/chained

**Comment by hubeyb** [comment]
Thanks...
