### ISSUE TITLE
error when special string in option value

### ISSUE THREAD

**Issue by poolerMF** [xavierfaucon/bootstrap-selectsplitter#5]
hello ... try to update script and change:

```
self.$element.find('option[value=' + self.currentChildCategory + ']').attr('selected', 'selected');
```

to:

```
self.$element.find('option[value="' + self.currentChildCategory + "']').attr('selected', 'selected');
```

this should by changed in updateParentCategory and updateChildCategory

**Comment by X13454** [comment]
Yes you're right, will update this one tomorrow.

**Comment by X13454** [comment]
Hi,

Version 0.1.3 has been published ; this problem should be resolved with your code.

Thank you for the tip.

Working fiddle:
http://jsfiddle.net/ae7fxdyy/19/
