### ISSUE TITLE
problem when using more select splitters

### ISSUE THREAD

**Issue by poolerMF** [xavierfaucon/bootstrap-selectsplitter#6]
when I use your code, there is problem with more splitters on same page ...

I'm using template METRONIC .. and they solved it:
http://www.keenthemes.com/preview/metronic/theme/assets/global/plugins/bootstrap-selectsplitter/bootstrap-selectsplitter.js

try to update your code ...

**Comment by X13454** [comment]
Hello, Thank you for your feedback. 

Will look at that tomorrow.

**Comment by xavierfaucon** [comment]
I cannot manage to reproduce your error ?
http://jsfiddle.net/ae7fxdyy/17/

**Comment by X13454** [comment]
Hi,

Version 0.1.3 has been published ; the problem looks resolved using keenthemes code.

Thank you for the tip.

Working fiddle:
http://jsfiddle.net/ae7fxdyy/19/
