### ISSUE TITLE
order of optgroup label is not maintained

### ISSUE THREAD

**Issue by fcryan** [xavierfaucon/bootstrap-selectsplitter#7]
just like in the other issue "order is not maintained" for the option value's... which is fixed... The order of optgroup label is not the same as how it it specified in html... sorts in asc

**Comment by X13454** [comment]
Hello,

Thanks for the feedback. I will correct it monday I think, won't have my computer this weekend.

**Comment by xavierfaucon** [comment]
I looked at it but I am not sure I can reproduce the error you are describing: Example:
http://jsfiddle.net/ae7fxdyy/31/

**Comment by X13454** [comment]
I looked at it but I am not sure I can reproduce the error you are describing.

Example:
http://jsfiddle.net/ae7fxdyy/35/

Could you please provide a fiddle with the problem encountered?

**Comment by fcryan** [comment]
Yup your fiddle sure works as expected. .thanks for your time... I'll check back in on my implimentation and/or the js that came with the theme after the holidays... thanks again great piece of code

**Comment by X13454** [comment]
Ok perfect. Do not hesitate if you have any problem!

And if you like it, you can star it :)
