### ISSUE TITLE
Multile Select

### ISSUE THREAD

**Issue by umarmughal** [xavierfaucon/bootstrap-selectsplitter#8]
Any chance to select multiple values? so if we select two on left side this will show both selected values on right side, please advice.

**Comment by X13454** [comment]
Interesting suggestion! I will keep it in mind and see if it can be implemented.

**Comment by X13454** [comment]
Hello, this feature looks interesting however I currently do not have the time to develop it. 
Feel free to do a PR.

**Comment by poolerMF** [comment]
I created multiselectsplitter from actual selctsplitter script with more options.

https://github.com/poolerMF/bootstrap-multiselectsplitter

**Comment by X13454** [comment]
Hello!

Good job and thanks for the information :)
Also, I believe it resolves this issue ; those needing this feature can use your plugin.
