### ISSUE TITLE
Handling "change" events

### ISSUE THREAD

**Issue by 2CmPw6** [xavierfaucon/bootstrap-selectsplitter#9]
Hi,

Love this plugin!! Great work :)

I have an issue where I handle the "change" events of the selected item and pass the val of the select to an ajax method.

If I click on each option (going down the list, right select box) then click the previous option the val is lost, i.e. not passed as a "change" event.

Here is my jQuery code to handle the "change" event and pass the selected val to a get request:

``` javascript
    $(function(){
      $("select#select_selectsplitter").change(function(){
        $.get("/proc/ajax.php",{select_id:$(this).val()}, function(ajaxRes){
          $("div#displayData").html(ajaxRes);
        });
      });
    });
```

Any thoughts on this? If I use a vanilla select with optgroups the val isn't lost, so its seems the issue is with selectsplitter :(

Cheers,

Jay

**Comment by X13454** [comment]
Hello,

Thanks for the feedback. I will not have access to my computer for the 2 next weeks (holidays :) )but I will review that issue before the end of the month.

Xavier

**Comment by X13454** [comment]
Hello,

OK I managed to reproduce the error.

http://jsfiddle.net/ae7fxdyy/91/

Will work on it

**Comment by 2CmPw6** [comment]
Hey!

Just got back from vacation too :)

Thanks for this dude, your solution works in my app too.

Cheers,

Jay

**Comment by X13454** [comment]
Hello,

The code was updated (version 0.1.4) and should resolve this error.
Please reopen if it is not solving your issue.

Cheers,

Xavier
